### ISSUE TITLE
Empty file in pretraining VQA

### ISSUE THREAD

**Issue by KfirBernstein** [airsplay/lxmert#38]
Hi,

I'm doing as you wrote in the readme file
Now when I'm running:
` bash run/vqa_finetune.bash 0 vqa_lxr955_tiny --tiny`

I get the following error:

> Load 632117 data from split(s) train,nominival.
> Start to load Faster-RCNN detected objects from data/mscoco_imgfeat/train2014_obj36.tsv
> Loaded 512 images in file data/mscoco_imgfeat/train2014_obj36.tsv in 2 seconds.
> Start to load Faster-RCNN detected objects from data/mscoco_imgfeat/val2014_obj36.tsv
> Loaded 512 images in file data/mscoco_imgfeat/val2014_obj36.tsv in 2 seconds.
> Use 2888 data in torch dataset
> 
> Load 25994 data from split(s) minival.
> Start to load Faster-RCNN detected objects from data/mscoco_imgfeat/val2014_obj36.tsv
> Loaded 512 images in file data/mscoco_imgfeat/val2014_obj36.tsv in 2 seconds.
> Use 2618 data in torch dataset
> 
> Traceback (most recent call last):
>   File "/StudentData/lxmert-master/name_of_environment/lib/python3.5/tarfile.py", line 2281, in next
>     tarinfo = self.tarinfo.fromtarfile(self)
>   File "/StudentData/lxmert-master/name_of_environment/lib/python3.5/tarfile.py", line 1083, in fromtarfile
>     obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
>   File "/StudentData/lxmert-master/name_of_environment/lib/python3.5/tarfile.py", line 1019, in frombuf
>     raise EmptyHeaderError("empty header")
> tarfile.EmptyHeaderError: empty header
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "src/tasks/vqa.py", line 178, in <module>
>     vqa = VQA()
>   File "src/tasks/vqa.py", line 48, in __init__
>     self.model = VQAModel(self.train_tuple.dataset.num_answers)
>   File "/StudentData/lxmert-master/src/tasks/vqa_model.py", line 21, in __init__
>     max_seq_length=MAX_VQA_LENGTH
>   File "/StudentData/lxmert-master/src/lxrt/entry.py", line 95, in __init__
>     mode=mode
>   File "/StudentData/lxmert-master/src/lxrt/modeling.py", line 769, in from_pretrained
>     with tarfile.open(resolved_archive_file, 'r:gz') as archive:
>   File "/StudentData/lxmert-master/name_of_environment/lib/python3.5/tarfile.py", line 1577, in open
>     return func(name, filemode, fileobj, **kwargs)
>   File "/StudentData/lxmert-master/name_of_environment/lib/python3.5/tarfile.py", line 1631, in gzopen
>     t = cls.taropen(name, mode, fileobj, **kwargs)
>   File "/StudentData/lxmert-master/name_of_environment/lib/python3.5/tarfile.py", line 1607, in taropen
>     return cls(name, mode, fileobj, **kwargs)
>   File "/StudentData/lxmert-master/name_of_environment/lib/python3.5/tarfile.py", line 1470, in __init__
>     self.firstmember = self.next()
>   File "/StudentData/lxmert-master/name_of_environment/lib/python3.5/tarfile.py", line 2296, in next
>     raise ReadError("empty file")
> tarfile.ReadError: empty file

Thanks!

**Comment by airsplay** [comment]
I am not sure about this issue. It might come from some disk/network error.
