### ISSUE TITLE
GQA submission

### ISSUE THREAD

**Issue by zaynmi** [airsplay/lxmert#52]
I generated the `submit_predict.json` and submited it to GQA evaluation server. However, I got an accuracy of 0 in test phase, but the result in dev phase makes sense. Is it possible that I predict all wrong answers in test split?

What is wrong with the submission file?

**Comment by airsplay** [comment]
1. Are you submitting to GQA 2020 or GQA 2019? The code was built based on GQA2019, the organizer might change the data in 2020.

2. Have you checked the ques_id inside the json file? Is it consistent with the challenge they provided? Is the format of the ques_id / answer correct (int/str)? 

3. Please also check the size of submit_predict.json. It should be very large to include the answers to all questions.

**Comment by runzeer** [comment]
@zaynmi
Have you solved the problem? I encountered the same problem. If you solved it, could you please tell me the reason?

**Comment by zaynmi** [comment]
@runzeer Sorry, I haven't solve it. The organizer did release a new test set. However, I checked the `submission_all_questions.json` in GQA questions v1.3 and v1.1 and they are the same.  
I think probably, there are bugs in GQA 2020 server or they change the rules that I didn't figure out.

**Comment by airsplay** [comment]
The GQA test server would provide the testing log here, could you try to find some more info there?
![image](https://user-images.githubusercontent.com/2796554/80820680-5a5b0280-8ba5-11ea-8356-64e27a2d47b3.png).

I am not attending the GQA challenge this year so I am not aware of all the details. For the challenge last year (GQA 2019), I followed the instruction in this README to submit the prediction file and the results could be checked on the leaderboard.

**Comment by runzeer** [comment]
@airsplay  I checked the testing log. It has nothing with the results. And the evaluation is finished but the accuracy is 0. So if convenient, could you help find the issues? Thanks a lot!!

**Comment by airsplay** [comment]
Would you mind to share the log files on the GQA testing servers? And could you share the test-dev test results with its logs? Thus it would be easy to figure out.

**Comment by runzeer** [comment]
@airsplay Thanks for your reply!
**The results and logs for test are listed as below:**
{"Accuracy": 0, "Binary": 0, "Open": 0, "Validity": 0, "Plausibility": 0, "Distribution": -0.01}
Starting Evaluation.....
Loading questions...
Loading predictions...
Completed evaluation for test2020 Phase

**The results and logs for test-dev are listed as below:**
{"Accuracy": 56.77368833202819, "Binary": 73.13664596273291, "Open": 40.12638230647709, "Validity": 97.5724353954581, "Plausibility": 88.9584964761159, "Distribution": 0.31118867544640394}
Starting Evaluation.....
Loading questions...
Loading predictions...
Completed evaluation for dev2020 Phase

I can not figure out the results from the logs.

**Comment by airsplay** [comment]
Thanks! It's hard to tell why... But at least we found an **impossible number** in this results: **`"Distribution": -0.01`**. It seems to be some error in the **online evaluation scripts / submitted result files**. 

Could you also share Stdout File & Stderr File?

By the way, have you modified the code?  If the code and dev set are all the same, the results of dev2020 should be around 58~59%, but it seems that the dev2020 here is 56%.

**Comment by runzeer** [comment]
The  content for the Stdout File  is  below
Starting Evaluation.....
Loading questions...
Loading predictions...
Completed evaluation for dev2020 Phase

The Stderr File is None.

For the different results, I just modified some codes and randomly selected one result for check. It seemed normal lower than thr original

**Comment by airsplay** [comment]
It's strange...

Is it possible to check whether the original code suffering from the same issue? The weight is available here: https://github.com/airsplay/lxmert/issues/16

**Comment by runzeer** [comment]
My colleage have tested this. It is also the same.

**Comment by airsplay** [comment]
That's crazy... I will try to figure it out soon. My servers are all running now for some long experiments...

**Comment by runzeer** [comment]
Thanks very much ！ I also emailed the author but received no reply.

**Comment by airsplay** [comment]
Thanks. I think that it is a common issue in GQA 2020 this year... Currently, the leaderboard of test 2020 was still empty (I am not sure whether it is intended or not).

In the first time of submission, I tested the results and get some error logs here:
```
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 426, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmpbxpi00ad/compute/challenge_data/challenge_541/main.py", line 76, in evaluate
    with open(user_submission_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbxpi00ad/compute/submission_files/submission_71692/2673de7d-77d1-4477-ae12-1a265892bcf0.json' 
```

And on the second time, I get the same results as you:
```
{"Accuracy": 0, "Binary": 0, "Open": 0, "Validity": 0, "Plausibility": 0, "Distribution": -0.01}
```

It seems that it is a problem of evaluation servers. I believe that there would be some explanations soon.

**Comment by runzeer** [comment]
Thanks very much! I would continue contacting the author and hope to find the issues.

**Comment by j-min** [comment]
Are there any updates on GQA 2020 @runzeer @airsplay?

**Comment by airsplay** [comment]
@j-min No news on my side :(...

**Comment by dorarad** [comment]
Hello everybody!

Thank you very much for the interest in the dataset and the challenge, and I would like to begin by the most honest and sincere apology for replying so late. Due to an unexpected personal difficulty in recent months I wasn't available in email and couldn't run the challenge over the spring. I do  apologize a lot for any inconvenience this might have caused.

In case you might be interested in that, I'm happy and excited to let you know that the 2020 GQA competition has been accordingly rescheduled and will take place over the summer. I'm actively working currently to release the updated test set that will be used for evaluation (training and dev sets remain the same, as well as the data distribution). See http://visualreasoning.org/challenge.html for further details and timeline, hope to see you there! 

To respond to your questions above, there was a technical issue with the settings of the 2020 challenge, and I therefore locked it for now. I will work to fix them and reopen it in the next few weeks. In the meantime, please feel free to develop your models over the 2019 version, which is also open on evalAI. 

The differences between 2019 and 2020 will only be in the test set, rather than training/dev with the data distribution remaining exactly the same. The only difference between them will be that we will evaluate the models by having less questions per image (3 as in VQA, rather than dozens per image). This change therefore shouldn't be expected to alter your performance beyond a minor randomly statistical impact (different randomly sampled questions/images), so until it's online you should feel confident developing and evaluating your models using the currently open 2019 portal.

Best regards and please let me know if you have any further questions and I will be most happy to help, I do apologize again for the large delay in my response!
